config/routes.rb
Rails.application.routes.draw do
  root "splash#index"

  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'password',
    confirmation: 'verification',
    unlock: 'unlock',
    sign_up: 'signup',
    edit: 'edit'
  }, controllers: { registrations: 'registrations'}

  resources :categories, only: [:index, :new, :create] do
    resources :transactions, only: [:index, :new, :create]
  end

  # get "categories", to: "categories#index", as: :home
  # get "transactions", to: "transactions#transactions_page", as: :transactions
  # get "categories/new", to: "categories#new", as: :new_category
  # get "transactions/new", to: "transactions#new", as: :new_transaction

  # post "categories", to: "categories#create"

  delete "logout", to: "devise/sessions#destroy", as: :logout

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, Group, user_id: user.id
    can :manage, Operation, author_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user, class_name: 'User'
  mount_uploader :icon, IconUploader

  has_many :group_operations, dependent: :destroy
  has_many :operations, through: :group_operations

  validates :name, :icon, presence: true

  def owned_by?(user)
    user_id == user.id
  end
end

app/models/group_operation.rb
class GroupOperation < ApplicationRecord
  belongs_to :group
  belongs_to :operation

  validates :operation, :group, presence: true
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_operations, dependent: :destroy
  has_many :groups, through: :group_operations

  validates :name, presence: true
  validates :amount, presence: true, numericality: { allow_nil: false }

  def owned_by?(user)
    author_id == user.id
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :operations, foreign_key: 'author_id', dependent: :destroy
  has_many :groups

  validates :name, presence: true, length: { minimum: 3 }
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  def can_manage_group?(group)
    group.owned_by?(self)
  end

  def can_manage_operation?(operation)
    operation.owned_by?(self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(_resource)
    categories_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @group = current_user.groups
  end

  def new_category_page
    @category = Group.new
  end

  def create
    @category = Group.new(category_params)
    @category.user_id = current_user.id

    if @category.save
      redirect_to categories_path, notice: 'Category created!'
    else
      render new_category_path
    end
  end

  # def new_category_page; end

  private

  def category_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home_page; end
end

app/controllers/registrations_controller.rb
# app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def splash_page; end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @category = Group.find(params[:category_id])
    puts @category.inspect
    @transactions = @category.operations.order(created_at: :desc)
    puts @transactions.inspect
    @total_amount = @transactions.sum(:amount)
  end

  def new
    @category = Group.find(params[:category_id])
    @transaction = @category.operations.new
  end

  def create
    @category = Group.find(params[:category_id])
    @transaction = @category.operations.new(transaction_params)
    @transaction.author_id = current_user.id

    if @transaction.save
      puts "params: #{params.inspect}"
      puts "params[:operation]: #{params[:operation].inspect}"

      group_id = params[:category_id]
      GroupOperation.create(group_id:, operation_id: @transaction.id)

      redirect_to category_transactions_path(@category), notice: 'Transaction created!'
    else
      puts @transaction.errors.inspect
      flash[:error] = @transaction.errors.full_messages.join(', ')
      render :new
    end
  end

  private

  def transaction_params
    params.require(:operation).permit(:name, :amount, group_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/categories/index.html.erb
<div class="container">
    <div class="header blue">
      <div class="transaction-title">  
        <a href="<%= root_path %>">
          <%= image_tag("arrow.png", class: "back") %>
        </a>
        <h1 class="main-title login-title">CATEGORIES</h1>
        <%= image_tag("search.png", class: "back") %>
      </div>  
      <div class="recent-ancient">
        <p class="before"></p>
        <div class="recent">
          <p>Most recent</p>
          <div class="dot"></div>
        </div>
        <p class="ancient">Most ancient</p>
      </div>
    </div>

    <div class="group-sum">
      <h1>Gift credit</h1>
      <p class="total-sum">$0.00</p>
    </div>

    <hr class="big-separator">

    <% @group.each do |category| %>
      <div onclick="window.location='<%= category_transactions_path(category_id: category.id) %>';" class="categories">
      <%= image_tag category.icon.url if category.icon.present? %>
        <div class="name-date">
          <p><%= category.name %></p>
          <p class="date"><%= category.created_at.strftime("%d %b %y") %></p>
        </div>  
        <p class="amount">$<%= category.operations.sum(:amount) %></p>
      </div>
      <hr class="separator">
    <% end %>

  <a href="<%= new_category_path %>" class="bottom-button green">
    <p>NEW CATEGORY</p>
  </a>
</div>

app/views/categories/new.html.erb
<div class="container">
    <div class="header blue">
      <div class="transaction-title">  
        <a href="<%= categories_path %>">
          <%= image_tag("arrow.png", class: "back") %>
        </a>
        <h1 class="main-title login-title">ADD CATEGORY</h1>
        <%= image_tag("search.png", class: "back") %>
      </div>  
    </div>
    
    <%= form_with(model: @category, url: categories_path, local: true, class: "new-form") do |form| %>
      <%= form.fields_for :group do |group_form| %>
        <div class="field">
          <%= group_form.text_field :name, required: true, class: "input", placeholder: "Name" %>
        </div>
        <div class="field upload-picture">
          <%= image_tag("user.png", class: "sample-picture") %>
          <p>Upload icon</p>
          <%= group_form.file_field :icon, required: true, class: "input", placeholder: "Upload icon"  %>
        </div>
      <% end %> 
    <div class="new-button-container">
      <%= form.submit "CREATE", class:"new-button green" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/splash/index.html.erb
<div class="container splash">
    <h1 class="budgy">Budgy</h1>

    <div class="buttons">
        <p class="login"><a href="<%= new_user_session_path %>">LOG IN</a></p>

        <p class="signup"><a href="<%= new_user_registration_path %>">SIGN UP</a></p>  
    </div>
</div>

app/views/transactions/index.html.erb
<div class="container">
    <div class="header blue">
      <div class="transaction-title">  
        <a href="<%= categories_path %>">
          <%= image_tag("arrow.png", class: "back") %>
        </a>
        <h1 class="main-title login-title">TRANSACTIONS</h1>
        <%= image_tag("search.png", class: "back") %>
      </div>  
      <div class="recent-ancient">
        <p class="before"></p>
        <div class="recent">
          <p>Most recent</p>
          <div class="dot"></div>
        </div>
        <p class="ancient">Most ancient</p>
      </div>
    </div>

<div class="group-sum">
  <h1><%= @category.name %></h1>
  <p class="total-sum">$<%= @total_amount %></p>
</div>
<hr class="big-separator">
    <% @transactions.each do |transaction| %>
      <div class="categories">
        <%= image_tag @category.icon.url if @category.icon.present? %>
        <div class="transaction-name-date">
          <p><%= transaction.name %></p>
          <p class="date"><%= transaction.created_at.strftime("%d %b %y") %></p>
        </div>
          <p class="amount">$<%= transaction.amount %></p>
      </div>
      <hr class="separator">
    <% end %>

<a href="<%= new_category_transaction_path(category_id: @category.id) %>" class="bottom-button green">
  <p>NEW TRANSACTION</p>
</a>

</div>

app/views/transactions/new.html.erb
<div class="container new-category">
    <div class="header blue">
      <div class="transaction-title">  
        <a href="<%= category_transactions_path(category_id: @category.id) %>">
          <%= image_tag("arrow.png", class: "back") %>
        </a>
        <h1 class="main-title login-title">ADD TRANSACTION</h1>
        <%= image_tag("search.png", class: "back") %>
      </div>  
    </div>

  <% if flash[:error] %>
    <div class="alert alert-danger">
      <%= flash[:error] %>
    </div>
  <% end %>

  <%= form_with model: [@category, @transaction], url: category_transactions_path(@category) do |form| %>
    <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>
      <ul>
        <% @transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= form.text_field :name, required: true, class: "input", placeholder: "Name"  %>
    </div>

    <div class="field">
      <%= form.number_field :amount, required: true, class: "input", placeholder: "Amount" %>
    </div>

    <div class="new-button-container">
      <%= form.submit "Save", class: "new-button green" %>
    </div>
  <% end %>
</div>